baseurl = "http://alexlarioza.com/"
title = "Who is Alex Larioza?!"
languageCode = "en-us"
publishDir = "public"
googleAnalytics  = "UA-114648620-1"

[permalinks]
  blog = "blog/:year/:month/:title/"

[params]
    mugshot = "/images/mugshot3.jpg"
	description = "I make cool stuff"
    name = "Alex Larioza"
    titles = "game developer. designer. photographer. nerd. juggler. animal lover. hiker. creator. boardgame geek. cat fancier. explorer. food enthusiast. gamer. outdoorsman."
    social = [
        ["", "fas fa-envelope", "mailto:contact@alexlarioza.com"],
        ["", "fab fa-linkedin", "https://www.linkedin.com/in/alexlarioza"],
        ["", "fab fa-github", "https://github.com/SHiLLySiT"],
        ["", "fab fa-flickr", "https://www.flickr.com/photos/alexlarioza"],
        ["", "fab fa-instagram", "https://www.instagram.com/shillysit"],
    ]
    keywords = """video games, games, cats, meow, cat, android, ios, steam, 
    alex, larioza, material, abstract, design, development, programming,
    developer, studio, unity, unity3d, mobile, fun, bored, madison, 
    wisconsin, indie, solo, dev, arcade, puzzle, app, apple, google, play"""