{
  mugshot: "media/mugshot.jpg",
  name: "Alex Larioza",
  description: "game developer. designer. photographer. nerd. programmer. juggler. sourdough baker. problem solver. animal lover. hiker. creator. boardgame geek. cat fancier. explorer. food enthusiast. kombucha brewer. gamer. outdoorsman. tinkerer.",
  social: [
    ["Email", "fas fa-envelope", "mailto:contact@alexlarioza.com"],
    ["Linkedin", "fab fa-linkedin", "https://www.linkedin.com/in/alexlarioza"],
    ["Github", "fab fa-github", "https://github.com/SHiLLySiT"],
    ["Flicker", "fab fa-flickr", "https://www.flickr.com/photos/alexlarioza"],
  ],
  companies: {
    default: {
      name: "Alex Larioza",
      icon: "/media/company-logos/default.png",
    },
    filament: {
      name: "Filament Games",
      icon: "/media/company-logos/filament.png",
    },
    humanhead: {
      name: "Human Head Studios",
      icon: "/media/company-logos/humanhead.png",
    },
    wgbh: {
      name: "WGBH",
      icon: "/media/company-logos/wgbh.png",
    },
    quantum: {
      name: "Quantum Astrophysics Guild",
      icon: "/media/company-logos/quantum.png",
    },
    bulletproof: {
      name: "Bullet Proof Arcade",
      icon: "/media/company-logos/bulletproof.png",
    },
  }
}