{
  mugshot: "/media/mugshot.jpeg",
  name: "Alex Larioza",
  description: "game developer. designer. photographer. nerd. programmer. star gazer. technical writer. juggler. sourdough baker. problem solver. animal lover. hiker. creator. boardgame geek. cat fancier. explorer. food enthusiast. kombucha brewer. gamer. outdoorsman. tinkerer.",
  social: [
    ["Email", "fas fa-envelope", "mailto:contact@alexlarioza.com"],
    ["Linkedin", "fab fa-linkedin", "https://www.linkedin.com/in/alexlarioza"],
    ["Github", "fab fa-github", "https://github.com/SHiLLySiT"],
    ["Flicker", "fab fa-flickr", "https://www.flickr.com/photos/alexlarioza"],
  ],
  projectTypes: {
    game: { 
      icon: "fa-solid fa-gamepad",
      name: "GAME",
    },
    article:  { 
      icon: "fa-solid fa-file-lines",
      name: "ARTICLE",
    },
    app:  { 
      icon: "fa-solid fa-display",
      name: "APP",
    },
    website:  { 
      icon: "fa-solid fa-earth-americas",
      name: "WEBSITE",
    },
    code:  { 
      icon: "fa-brands fa-github",
      name: "CODE",
    }
  },
  companies: {
    default: {
      name: "Alex Larioza",
      icon: "/media/company-logos/default.png",
    },
    filament: {
      name: "Filament Games",
      icon: "/media/company-logos/filament.png",
    },
    humanhead: {
      name: "Human Head Studios",
      icon: "/media/company-logos/humanhead.png",
    },
    wgbh: {
      name: "WGBH",
      icon: "/media/company-logos/wgbh.png",
    },
    quantum: {
      name: "Quantum Astrophysics Guild",
      icon: "/media/company-logos/quantum.png",
    },
    bulletproof: {
      name: "Bullet Proof Arcade",
      icon: "/media/company-logos/bulletproof.png",
    },
    flippfly: {
      name: "Flippfly",
      icon: "/media/company-logos/flippfly.png",
    },
  },
  # TODO: implement quote somewhere
  quotes: {
    # random
    "I'm not really sure what to put here",
    "This tagline is randomized if you haven't notice already",
    "click me!",
    "meow",
    "insert random quote here",

    # skyrim
    "I used to be an adventurer like you then I took an arrow in the knee",
    "Iron Sword Huh? What Are You Killing? Butterflies?",
    "No Lollygaggin'",
    "Let Me Guess, Someone Stole Your Sweetroll?",
    "You'll Make A Fine Rug, Cat!",

    # rick roll, duh
    "Never gonna give you up Never gonna let you down",

    # zero wing
    "all your base are belong to us",

    # legend of zelda
    "It's dangerous to go alone, take this",

    # the expanse
    "legitimate salvage",
    
    # it crowd
    "hello I.T. have you tried turning it off and on again",

    # stargate
    "indeed",
    "The Setesh guard's nose drips",

    # bioshock
    "We all make choices in life but in the end our choices make us",
    
    # outer wilds
    "science compels us to explode the sun",
    "The future depends on the past, even if we don't get to see it",

    # fringe
    "HELLO PETER, THIS IS ME, YOUR FATHER, WALTER BISHOP"
  }
}